### ISSUE TITLE
Direction of rotation

### ISSUE THREAD

**Issue by 5im0n** [castorflex/FlipImageView#2]
Hey Castorflex,

Have you planned something for the direction of rotation ?

For the time being if we only activate Y rotation the direction is clockwise.

**Comment by castorflex** [comment]
Should be ok now, you can reverse the rotation through xml or code. Just tell me if you have issues.

**Comment by 5im0n** [comment]
Thank you for your responsiveness!
I've already try this kind code yesterday by changing the local variable forward:

``` java
if (forward) {
                degrees = -degrees;
 }
```

The problem is that it works only for Z rotation.

**Comment by castorflex** [comment]
Ok I'll have a look when I have time. Thx for your feedback.
